### ISSUE TITLE
Integration with Discord/Slack: GitHub Integrations Get notified about new issues, comments, task updates

### ISSUE THREAD

**Issue by dahlwinters** [terranexum/FlowGrow#6]
Set up a GitHub integration with Discord so that contributors in our Discord can be notified about new issues, comments, and task updates.

**Comment by AwesomeMarker100** [comment]
Got integration with Discord down

**Comment by dahlwinters** [comment]
@AwesomeMarker100 awesome! I'm seeing the #github-updates channel, looks like it's working great, this issue is definitely closed
